# fly.toml app configuration file generated for swiss-mud-client on 2025-05-08T22:00:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swiss-mud-client'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  VITE_WS_URL = "wss://swiss-mud-proxy.fly.dev"
